# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0
  
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-18-lein-2.9.8-buster-node-browsers-legacy
    steps:
      - checkout
      - run : mvn test
      - store_artifacts:
          path:  target